INSERT OR IGNORE INTO rss_sources (name, url, tier, category) VALUES
  ('247Sports Auburn Undercover', 'https://247sports.com/college/auburn/feeds/rss', 1, 'FOOTBALL'),
  ('AL.com Auburn Sports', 'https://al.com/arc/outboundfeeds/rss/category/sports/college/auburn-tigers/', 1, 'FOOTBALL'),
  ('On3 Auburn Tigers', 'https://on3.com/teams/auburn-tigers/feed/', 1, 'FOOTBALL'),
  ('Auburn Athletics Official', 'https://auburntigers.com/common/feeds/rss.aspx', 1, 'FOOTBALL'),
  ('Google News Auburn Football', 'https://news.google.com/rss/search?q=Auburn+football&hl=en-US&gl=US&ceid=US:en', 1, 'FOOTBALL'),
  ('Bleacher Report Auburn', 'https://bleacherreport.com/auburn-football.rss', 1, 'FOOTBALL'),
  ('On3 Transfer Portal', 'https://on3.com/transfer-portal/feed/', 2, 'PORTAL'),
  ('247Sports Transfer Portal', 'https://247sports.com/TransferPortal/feeds/rss', 2, 'PORTAL'),
  ('Google News Transfer Portal SEC', 'https://news.google.com/rss/search?q=transfer+portal+SEC+football', 2, 'PORTAL'),
  ('Google News Auburn Transfer', 'https://news.google.com/rss/search?q=Auburn+transfer+portal', 2, 'PORTAL'),
  ('On3 NIL News', 'https://on3.com/nil/feed/', 3, 'NIL'),
  ('Sports Illustrated College Football', 'https://si.com/college/rss', 3, 'NIL'),
  ('Google News Auburn NIL', 'https://news.google.com/rss/search?q=Auburn+NIL+football', 3, 'NIL'),
  ('Google News SEC NIL Spending', 'https://news.google.com/rss/search?q=SEC+NIL+spending+football', 3, 'NIL'),
  ('Google News SEC Football', 'https://news.google.com/rss/search?q=SEC+football', 4, 'SEC'),
  ('Google News Auburn NFL', 'https://news.google.com/rss/search?q=Auburn+Tigers+NFL', 4, 'SEC'),
  ('ESPN College Football', 'https://www.espn.com/espn/rss/ncf/news', 4, 'SEC'),
  ('CBS Sports College Football', 'https://www.cbssports.com/rss/headlines/college-football/', 4, 'SEC');
